Updating README, minor alloc.c warnings, and updating actuator/radio usage of SPI.

diff --git a/.github/workflows/cmake-check.yml b/.github/workflows/cmake-check.yml
--- a/.github/workflows/cmake-check.yml
+++ b/.github/workflows/cmake-check.yml
@@ -34,3 +34,6 @@ jobs:
             echo "Building ${target}.elf"
             make "${target}.elf"
           done
+          cd ../../
+          gcc -std=c18 -Wall -Wextra ./src/internal/alloc.c ./test/test_alloc.c -o src/build/test_alloc || { echo "Compile test_alloc failed"; exit 21; }
+          echo "Built target test_alloc"
